spring:
  application:
    name: greeting-service
     
greeting-service:
  greeting: "Olá"
  default-value: "Mundo"
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
    
server:
  address: 127.0.0.1
  port: 8081
